// Timed captions for a clip: seconds-based segments, rendered as an overlay
// during muted autoplay. Generated by Whisper (see /api/videos/captions).

// One spoken word with its own start/end, for karaoke-style captions where the
// active word is highlighted as it's said. Optional — older captions (and clips
// transcribed before word timing was requested) only carry segment timing.
export type CaptionWord = { text: string; start: number; end: number };
export type CaptionSegment = { start: number; end: number; text: string; words?: CaptionWord[] };

// Coerce arbitrary JSON (DB or request) into clean segments, or null.
export function parseCaptions(json: unknown): CaptionSegment[] | null {
  if (!Array.isArray(json) || json.length === 0) return null;
  const out: CaptionSegment[] = [];
  for (const raw of json) {
    if (!raw || typeof raw !== "object") continue;
    const r = raw as Record<string, unknown>;
    const start = Number(r.start);
    const end = Number(r.end);
    const text = typeof r.text === "string" ? r.text.trim() : "";
    if (!Number.isFinite(start) || !Number.isFinite(end) || !text) continue;
    const seg: CaptionSegment = { start, end, text: text.slice(0, 200) };
    const words = parseWords(r.words);
    if (words) seg.words = words;
    out.push(seg);
  }
  return out.length ? out.slice(0, 400) : null;
}

// Clean a segment's per-word timings, dropping any that are malformed.
function parseWords(json: unknown): CaptionWord[] | null {
  if (!Array.isArray(json) || json.length === 0) return null;
  const out: CaptionWord[] = [];
  for (const raw of json) {
    if (!raw || typeof raw !== "object") continue;
    const r = raw as Record<string, unknown>;
    const start = Number(r.start);
    const end = Number(r.end);
    const text = typeof r.text === "string" ? r.text.trim() : "";
    if (!Number.isFinite(start) || !Number.isFinite(end) || !text) continue;
    out.push({ start, end, text: text.slice(0, 60) });
  }
  return out.length ? out.slice(0, 60) : null;
}
