// Hero demo: the two static photos an owner uploads, then the actual reel
// AfterShot rendered from them (public/demo-reel.mp4, made from these shots).
export default function DemoShowcase() {
  return (
    <div className="demo">
      <div className="demo-pair">
        <figure className="demo-shot">
          <img src="/real-before.jpg" alt="Driveway before pressure washing" />
          <figcaption className="tag before">BEFORE</figcaption>
        </figure>
        <figure className="demo-shot">
          <img src="/real-after.jpg" alt="Driveway after pressure washing" />
          <figcaption className="tag after">AFTER</figcaption>
        </figure>
      </div>
      <div className="demo-arrow" aria-hidden="true">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14"/><path d="m19 12-7 7-7-7"/></svg>
        <span>becomes this — automatically</span>
      </div>
      <div className="demo-phone">
        <video src="/demo-reel.mp4" autoPlay muted loop playsInline aria-label="Reel generated by AfterShot from the two photos above" />
      </div>
    </div>
  );
}
